services:
  app:
    container_name: litenetlib-referrer
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 7777:7777
    command: ["7777", "MyConnectionKey"] # Change this to your server's port and connection key